/**
 * Container Page Manager
 *
 * Manages public page serving for container Rachels.
 * Containers register pages via internal API → orchestrator maps
 * subdomain to container:port via nginx reverse proxy.
 *
 * URL format: {name}-{userId}.get-rachel.com
 * Port range: 10000–60000 (configurable)
 *
 * Storage: SQLite (pages.db) for persistence across restarts.
 * Nginx: Generates config and reloads on changes.
 * Heartbeat: Hourly check removes dead pages.
 */

import { Database } from "bun:sqlite";
import { log } from "./config";

// ---------- Types ----------

export interface PageRegistration {
  id: number;
  userId: string;
  name: string;
  containerPort: number;
  hostPort: number;
  subdomain: string;
  publicUrl: string;
  createdAt: string;
  lastSeen: string;
}

interface RegisterPageInput {
  userId: string;
  name: string;
  containerPort: number;
}

// ---------- Config ----------

const DB_PATH = process.env.PAGES_DB_PATH || "/home/rachel/rachel-cloud/data/pages.db";
const BASE_DOMAIN = process.env.PAGES_BASE_DOMAIN || "get-rachel.com";
const PORT_RANGE_START = parseInt(process.env.PAGES_PORT_START || "10000", 10);
const PORT_RANGE_END = parseInt(process.env.PAGES_PORT_END || "60000", 10);
const NGINX_CONF_PATH = process.env.PAGES_NGINX_CONF || "/etc/nginx/conf.d/rachel-pages.conf";

// ---------- Database ----------

let db: Database;

function initDb(): void {
  db = new Database(DB_PATH, { create: true });
  db.exec("PRAGMA journal_mode=WAL;");
  db.exec(`
    CREATE TABLE IF NOT EXISTS pages (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      container_port INTEGER NOT NULL,
      host_port INTEGER NOT NULL UNIQUE,
      subdomain TEXT NOT NULL UNIQUE,
      public_url TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      last_seen TEXT NOT NULL DEFAULT (datetime('now')),
      UNIQUE(user_id, name)
    );
    CREATE INDEX IF NOT EXISTS idx_pages_user ON pages(user_id);
    CREATE INDEX IF NOT EXISTS idx_pages_subdomain ON pages(subdomain);
  `);
  log.info("Page manager DB initialized", { path: DB_PATH });
}

// ---------- Port Allocation ----------

function allocatePort(): number {
  const usedPorts = db
    .query("SELECT host_port FROM pages")
    .all()
    .map((r: any) => r.host_port as number);

  const usedSet = new Set(usedPorts);

  for (let port = PORT_RANGE_START; port <= PORT_RANGE_END; port++) {
    if (!usedSet.has(port)) return port;
  }

  throw new Error("No available ports in range");
}

// ---------- Subdomain ----------

function buildSubdomain(name: string, userId: string): string {
  // Sanitize: lowercase, alphanumeric + hyphens only
  const safeName = name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 30);

  // Use first 8 chars of userId for brevity
  const shortId = userId.slice(0, 8);
  return `${safeName}-${shortId}`;
}

// ---------- Nginx Config ----------

function generateNginxConfig(): string {
  const pages = db.query("SELECT * FROM pages").all() as any[];

  if (pages.length === 0) {
    return "# No pages registered\n";
  }

  let conf = "# Auto-generated by Rachel Cloud Page Manager\n";
  conf += "# DO NOT EDIT — regenerated on page register/delete\n\n";

  for (const page of pages) {
    const containerName = `rachel-user-${page.user_id}`;
    conf += `# ${page.subdomain}.${BASE_DOMAIN} → ${containerName}:${page.container_port}\n`;
    conf += `server {\n`;
    conf += `    listen 80;\n`;
    conf += `    server_name ${page.subdomain}.${BASE_DOMAIN};\n\n`;
    conf += `    location / {\n`;
    conf += `        proxy_pass http://127.0.0.1:${page.host_port};\n`;
    conf += `        proxy_set_header Host $host;\n`;
    conf += `        proxy_set_header X-Real-IP $remote_addr;\n`;
    conf += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`;
    conf += `        proxy_set_header X-Forwarded-Proto $scheme;\n`;
    conf += `    }\n`;
    conf += `}\n\n`;
  }

  return conf;
}

async function writeNginxConfig(): Promise<void> {
  const conf = generateNginxConfig();

  try {
    await Bun.write(NGINX_CONF_PATH, conf);
    log.info("Nginx config written", { path: NGINX_CONF_PATH });
  } catch (err) {
    log.error("Failed to write nginx config", { error: String(err) });
    throw err;
  }
}

async function reloadNginx(): Promise<void> {
  try {
    const proc = Bun.spawn(["nginx", "-s", "reload"], {
      stdout: "pipe",
      stderr: "pipe",
    });
    await proc.exited;

    if (proc.exitCode !== 0) {
      const stderr = await new Response(proc.stderr).text();
      log.warn("Nginx reload returned non-zero", { exitCode: proc.exitCode, stderr });
    } else {
      log.info("Nginx reloaded");
    }
  } catch (err) {
    // Nginx might not be installed yet (dev mode)
    log.warn("Could not reload nginx (may not be installed)", { error: String(err) });
  }
}

// ---------- Docker Port Mapping ----------

/**
 * When a container registers a page, we need to set up a port forward
 * from the host to the container. Since containers are on rachel-net,
 * we use socat or iptables. For simplicity, we use a socat background process.
 */
async function startPortForward(
  userId: string,
  hostPort: number,
  containerPort: number,
): Promise<void> {
  const containerName = `rachel-user-${userId}`;

  // Kill existing socat for this host port
  try {
    Bun.spawn(["pkill", "-f", `socat.*TCP-LISTEN:${hostPort}`], {
      stdout: "ignore",
      stderr: "ignore",
    });
  } catch {
    // ignore
  }

  // Start socat to forward host:hostPort → container:containerPort
  const proc = Bun.spawn(
    [
      "socat",
      `TCP-LISTEN:${hostPort},fork,reuseaddr`,
      `TCP:${containerName}:${containerPort}`,
    ],
    {
      stdout: "ignore",
      stderr: "ignore",
    },
  );

  // Don't await — socat runs in background
  log.info("Port forward started", {
    hostPort,
    containerName,
    containerPort,
    pid: proc.pid,
  });
}

async function stopPortForward(hostPort: number): Promise<void> {
  try {
    const proc = Bun.spawn(["pkill", "-f", `socat.*TCP-LISTEN:${hostPort}`], {
      stdout: "ignore",
      stderr: "ignore",
    });
    await proc.exited;
    log.info("Port forward stopped", { hostPort });
  } catch {
    // ignore
  }
}

// ---------- Public API ----------

export function registerPage(input: RegisterPageInput): PageRegistration {
  const { userId, name, containerPort } = input;

  // Check if already registered
  const existing = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  if (existing) {
    // Update last_seen and return existing
    db.query("UPDATE pages SET last_seen = datetime('now') WHERE id = ?").run(
      existing.id,
    );
    return {
      id: existing.id,
      userId: existing.user_id,
      name: existing.name,
      containerPort: existing.container_port,
      hostPort: existing.host_port,
      subdomain: existing.subdomain,
      publicUrl: existing.public_url,
      createdAt: existing.created_at,
      lastSeen: new Date().toISOString(),
    };
  }

  const hostPort = allocatePort();
  const subdomain = buildSubdomain(name, userId);
  const publicUrl = `https://${subdomain}.${BASE_DOMAIN}`;

  db.query(
    `INSERT INTO pages (user_id, name, container_port, host_port, subdomain, public_url)
     VALUES (?, ?, ?, ?, ?, ?)`,
  ).run(userId, name, containerPort, hostPort, subdomain, publicUrl);

  const row = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  log.info("Page registered", { userId, name, subdomain, hostPort, containerPort });

  return {
    id: row.id,
    userId: row.user_id,
    name: row.name,
    containerPort: row.container_port,
    hostPort: row.host_port,
    subdomain: row.subdomain,
    publicUrl: row.public_url,
    createdAt: row.created_at,
    lastSeen: row.last_seen,
  };
}

export function deletePage(userId: string, name: string): boolean {
  const existing = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  if (!existing) return false;

  db.query("DELETE FROM pages WHERE user_id = ? AND name = ?").run(userId, name);
  log.info("Page deleted", { userId, name, hostPort: existing.host_port });

  return true;
}

export function listUserPages(userId: string): PageRegistration[] {
  const rows = db
    .query("SELECT * FROM pages WHERE user_id = ? ORDER BY created_at DESC")
    .all(userId) as any[];

  return rows.map((r: any) => ({
    id: r.id,
    userId: r.user_id,
    name: r.name,
    containerPort: r.container_port,
    hostPort: r.host_port,
    subdomain: r.subdomain,
    publicUrl: r.public_url,
    createdAt: r.created_at,
    lastSeen: r.last_seen,
  }));
}

export function listAllPages(): PageRegistration[] {
  const rows = db
    .query("SELECT * FROM pages ORDER BY created_at DESC")
    .all() as any[];

  return rows.map((r: any) => ({
    id: r.id,
    userId: r.user_id,
    name: r.name,
    containerPort: r.container_port,
    hostPort: r.host_port,
    subdomain: r.subdomain,
    publicUrl: r.public_url,
    createdAt: r.created_at,
    lastSeen: r.last_seen,
  }));
}

// ---------- Port Forwarding Lifecycle ----------

export async function activatePage(userId: string, name: string): Promise<void> {
  const page = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  if (!page) throw new Error(`Page not found: ${name} for user ${userId}`);

  await startPortForward(userId, page.host_port, page.container_port);
  await writeNginxConfig();
  await reloadNginx();
}

export async function deactivatePage(userId: string, name: string): Promise<void> {
  const page = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  if (!page) return;

  await stopPortForward(page.host_port);
  deletePage(userId, name);
  await writeNginxConfig();
  await reloadNginx();
}

// ---------- Full Register + Activate ----------

export async function registerAndActivatePage(
  input: RegisterPageInput,
): Promise<PageRegistration> {
  const page = registerPage(input);
  await startPortForward(input.userId, page.hostPort, input.containerPort);
  await writeNginxConfig();
  await reloadNginx();
  return page;
}

export async function deactivateAndDeletePage(
  userId: string,
  name: string,
): Promise<boolean> {
  const page = db
    .query("SELECT * FROM pages WHERE user_id = ? AND name = ?")
    .get(userId, name) as any;

  if (!page) return false;

  await stopPortForward(page.host_port);
  deletePage(userId, name);
  await writeNginxConfig();
  await reloadNginx();
  return true;
}

// ---------- Heartbeat ----------

export async function heartbeatSweep(): Promise<{
  checked: number;
  removed: number;
  errors: string[];
}> {
  const pages = listAllPages();
  let removed = 0;
  const errors: string[] = [];

  for (const page of pages) {
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 5000);

      const resp = await fetch(`http://127.0.0.1:${page.hostPort}/`, {
        signal: controller.signal,
        redirect: "follow",
      });
      clearTimeout(timeout);

      // Any response (even 404) means the server is alive
      // Update last_seen
      db.query("UPDATE pages SET last_seen = datetime('now') WHERE id = ?").run(
        page.id,
      );
    } catch {
      // Server is dead — remove it
      log.info("Heartbeat: dead page detected", {
        userId: page.userId,
        name: page.name,
        subdomain: page.subdomain,
      });

      try {
        await deactivateAndDeletePage(page.userId, page.name);
        removed++;
      } catch (err) {
        errors.push(
          `Failed to remove ${page.subdomain}: ${String(err)}`,
        );
      }
    }
  }

  log.info("Heartbeat sweep complete", {
    checked: pages.length,
    removed,
    errors: errors.length,
  });

  return { checked: pages.length, removed, errors };
}

// ---------- Startup ----------

let heartbeatInterval: ReturnType<typeof setInterval> | null = null;

export function startPageManager(): void {
  initDb();

  // Restore port forwards for existing pages
  const pages = listAllPages();
  for (const page of pages) {
    startPortForward(page.userId, page.hostPort, page.containerPort).catch(
      (err) => log.error("Failed to restore port forward", { page: page.subdomain, error: String(err) }),
    );
  }

  if (pages.length > 0) {
    writeNginxConfig().then(() => reloadNginx()).catch(
      (err) => log.warn("Failed to restore nginx config on startup", { error: String(err) }),
    );
  }

  // Daily heartbeat (every 24 hours)
  heartbeatInterval = setInterval(
    () => heartbeatSweep().catch((err) => log.error("Heartbeat error", { error: String(err) })),
    24 * 60 * 60 * 1000, // 24 hours
  );

  log.info("Page manager started", {
    dbPath: DB_PATH,
    baseDomain: BASE_DOMAIN,
    portRange: `${PORT_RANGE_START}-${PORT_RANGE_END}`,
    existingPages: pages.length,
  });
}

export function stopPageManager(): void {
  if (heartbeatInterval) {
    clearInterval(heartbeatInterval);
    heartbeatInterval = null;
  }
  if (db) db.close();
  log.info("Page manager stopped");
}
